ARG lnd_version=v0.14.1-beta

ARG balanceofsatoshis_tag=v11.27.0
ARG charge_lnd_tag=v0.2.8
ARG igniter_tag=1.0.0
ARG lntop_tag=v0.3.0
ARG perfectly_balanced_tag=v0.0.9
ARG rebalance_lnd_tag=v2.2
ARG suez_commit=335d430

ARG lws_tag=v4.3.0
ARG ttyd_commit=45f7b4e

FROM golang:1.17-${DEBIAN_VERSION} AS builder

ARG arch

WORKDIR /build

RUN apt-get update \
    && apt-get install -y curl git gnupg python3 python3-venv \
    # for building ttyd
    && apt-get install -y build-essential cmake libjson-c-dev libwebsockets-dev

# getting lnd
ARG lnd_version
RUN curl -sSL -o /build/lnd-linux-${arch}-${lnd_version}.tar.gz https://github.com/lightningnetwork/lnd/releases/download/${lnd_version}/lnd-linux-${arch}-${lnd_version}.tar.gz
RUN curl -sSL -o /build/manifest-guggero-${lnd_version}.sig https://github.com/lightningnetwork/lnd/releases/download/${lnd_version}/manifest-guggero-${lnd_version}.sig
RUN curl -sSL -o /build/manifest-${lnd_version}.txt https://github.com/lightningnetwork/lnd/releases/download/${lnd_version}/manifest-${lnd_version}.txt
RUN curl https://raw.githubusercontent.com/lightningnetwork/lnd/master/scripts/keys/guggero.asc | gpg --import
RUN cd /build && gpg --verify manifest-guggero-${lnd_version}.sig manifest-${lnd_version}.txt && tar xzf lnd-linux-${arch}-${lnd_version}.tar.gz && mv lnd-linux-${arch}-${lnd_version} /lnd

#####

# building lntop
ARG lntop_tag
RUN cd /build && git clone --depth 1 --branch ${lntop_tag} https://github.com/edouardparis/lntop.git
ENV GOARCH=${arch}
ENV GOOS=linux
RUN cd /build/lntop && mkdir bin && go build -o bin/lntop cmd/lntop/main.go

# extracting suez requirements
ARG suez_commit
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN cd /build && git clone https://github.com/prusnak/suez.git && cd suez && git checkout ${suez_commit} && /root/.local/bin/poetry export -f requirements.txt --output requirements.txt --without-hashes

# building lws & ttyd
ARG lws_tag
RUN cd /build && git clone --depth 1 --branch ${lws_tag} https://libwebsockets.org/repo/libwebsockets
RUN cd /build/libwebsockets && mkdir build && cd build && cmake .. -DLWS_WITH_LIBUV=ON && make && make install

ARG ttyd_commit
RUN cd /build && git clone https://github.com/tsl0922/ttyd.git && cd ttyd && git checkout ${ttyd_commit}
RUN cd /build/ttyd && mkdir build && cmake . && make

# VERSION_SPECIFIC_BUILD_STEPS

FROM node:16-${DEBIAN_VERSION}-slim

ARG balanceofsatoshis_tag
RUN npm i -g balanceofsatoshis@${balanceofsatoshis_tag}

RUN echo "deb http://deb.debian.org/debian ${DEBIAN_VERSION}-backports main" | tee -a /etc/apt/sources.list

RUN apt update \
    && apt upgrade -y \
    && apt install -y --no-install-recommends bc git jq procps python3 python3-pip python3-wheel screen sysstat tini vim nano micro tmux <VERSION_SPECIFIC_DEPENDENCIES> \
    # for ttyd
    && apt install -y libc6 libcap2 libssl1.1 libuv1 zlib1g \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

ARG charge_lnd_tag
RUN git clone --depth 1 --branch ${charge_lnd_tag} https://github.com/accumulator/charge-lnd.git /charge-lnd
RUN cd /charge-lnd && <INSTALL_MAYBE_NO_GRPC>
RUN cd /charge-lnd && python3 setup.py install
RUN rm -rf /charge-lnd

ARG igniter_tag
RUN git clone --depth 1 --branch ${igniter_tag} https://github.com/RooSoft/igniter.git /igniter
RUN chmod +x /igniter/igniter.sh

# NB: the --branch trick doesn't work for perfectly-balanced, because it has a branch named the same as the tag
ARG perfectly_balanced_tag
RUN git clone https://github.com/cuaritas/perfectly-balanced.git /perfectly-balanced && cd /perfectly-balanced && git checkout ${perfectly_balanced_tag}
RUN chmod +x /perfectly-balanced/perfectlybalanced.sh

ARG rebalance_lnd_tag
RUN git clone --depth 1 --branch ${rebalance_lnd_tag} https://github.com/C-Otto/rebalance-lnd.git /rebalance-lnd
RUN cd /rebalance-lnd && <INSTALL_MAYBE_NO_GRPC>

ARG suez_commit
RUN git clone https://github.com/prusnak/suez.git /suez && cd /suez && git checkout ${suez_commit}
COPY --from=builder /build/suez/requirements.txt /suez/requirements.txt
RUN pip3 install -r /suez/requirements.txt

COPY --from=builder /lnd/lncli /bin/
COPY --from=builder /build/lntop/bin/lntop /bin/
COPY --from=builder /usr/local/lib/libwebsockets.so /usr/local/lib/
COPY --from=builder /usr/local/lib/libwebsockets.so.19 /usr/local/lib/
COPY --from=builder /usr/local/lib/libwebsockets-evlib_uv.so /usr/local/lib/
ENV LD_LIBRARY_PATH /usr/local/lib/
COPY --from=builder /build/ttyd /usr/bin/
# VERSION_SPECIFIC_COPY_STEPS
COPY motd /etc/motd

# The node container already has an user called node, rename it
RUN groupmod --new-name lnshell node && usermod --login lnshell --move-home --home /home/lnshell node

USER lnshell
WORKDIR /home/lnshell

ARG version
RUN mkdir -p /home/lnshell/.local/bin
COPY --chown=lnshell:lnshell bin/* /home/lnshell/.local/bin/
RUN cd /home/lnshell/.local/bin/ && chmod o+x *
RUN echo "PATH=~/.local/bin:$PATH; export PATH" >> /home/lnshell/.bashrc
RUN echo "cat /etc/motd" >> /home/lnshell/.bashrc
RUN echo "${version}" > /home/lnshell/.lnshell-version

EXPOSE 7681

ENV APP_PASSWORD=

ENV USERNAME=umbrel

ENTRYPOINT /usr/bin/tini /usr/bin/ttyd -- --credential ${USERNAME}:${APP_PASSWORD} bash
